PATH = ~/DotQuest/configs/rofi
TO = ~/.config/rofi

rofi-dependencies:
	pacman -S rofi --noconfirm

rofi-config:
	mkdir -p $(TO)
	cp $(PATH)/colors-next.rasi $(TO)
	cp $(PATH)/colors.rasi $(TO)
	cp $(PATH)/config.rasi $(TO)

rofi: rofi-dependencies rofi-config
.PHONY rofi