PATH = ~/DotQuest/configs/hyprlock
TO = ~/.config/hypr

hyprlock-dependencies:
	yay -S hyprlock --noconfirm

hyprlock-config:
	cp $(PATH)/hyprlock.conf $(TO)

hyprlock: hyprlock-dependencies hyprlock-config
.PHONY hyprlock