PATH = ~/DotQuest/configs/waybar-cava
TO = ~/.config/waybar

waybar-cava-dependencies:
	yay -S waybar-cava --noconfirm

waybar-cava-config:
	mkdir -p $(TO)
	cp $(PATH)/config $(TO)
	cp $(PATH)/power_menu.xml $(TO)
	cp $(PATH)/style-dark.css $(TO)

waybar-cava: waybar-cava-dependencies waybar-cava-config
.PHONY waybar-cava